### ISSUE TITLE
Docs: Motivation why same-server followers should be excluded 

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#109]
On the following page in the docs https://fedify.dev/manual/send
there is a section about how to exclude followers who live on the same server as the sender of a message.

The paragraph needs a motivational section because as a Fedify user, I don’t understand why the followers on the same server as me should be excluded. They won’t get the Create activity that I send, right?

**Comment by dahlia** [comment]
Usually, you don't want to send messages through ActivityPub to followers on the same server because they share the same database, so there's no need to.

For example, if `@foo@example.com` creates a post, it's already stored in the database at example.com, so there's no need to send a `Create(Note)` activity to `@bar@example.com`, because `@bar@example.com` already has access to the post in the database.

Does this explain it well enough?

**Comment by mattes3** [comment]
Oh I see what you mean. Of course, this would be a good paragraph for the docs.

**Comment by melroy89** [comment]
Feel free to great my a pr
