### ISSUE TITLE
Clarify the relationship between shared inbox key dispatcher and authorized fetch

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#124]
In the docs, it says:

> [!TIP]
> We highly recommend configuring the shared inbox key dispatcher to avoid
> potential incompatibility issues with ActivityPub servers that require
> [authorized fetch] (i.e., secure mode).

[authorized fetch]: https://swicg.github.io/activitypub-http-signature/#authorized-fetch

I would like to know at which point in time this incompatibility could arise if I omit the shared inbox key dispatcher. Can you give us an example where it happens?

I am asking because I do not have such a dispatcher, and Threads rejects my follow requests. When I try it with the fedify cli instead, follow requests can successfully be sent to Threads! So, I thought maybe the missing dispatcher could be the reason?

**Comment by dahlia** [comment]
It's because your server cannot fetch the public key of an actor on Threads due to lack of signing (authorized fetch).  It's quite tricky to explain, but [this article](https://seb.jambor.dev/posts/understanding-activitypub-part-4-threads/#the-instance-actor) would help you:

![A diagram showing the infinite loop of public key fetches between activitypub.academy and threads.net](https://seb.jambor.dev/posts/understanding-activitypub-part-4-threads/infinite-fetch.webp)

**Comment by mattes3** [comment]
Ah, I see. I added an instance actor and used it inside a new shared inbox key dispatcher. But I saw that this has nothing to do with my app's inability to send a Follow to Threads. I will create a separate issue for that problem.
