### ISSUE TITLE
Use zod

### ISSUE THREAD

**Issue by alexgleason** [dahlia/fedify#38]
This library would benefit a lot from [zod](https://github.com/colinhacks/zod) schemas.

I've built some here: https://gitlab.com/soapbox-pub/mostr/-/blob/main/src/activitypub/schema.ts

It's needed to ensure the response actually matches the interface.

**Comment by dahlia** [comment]
Fedify doesn't just treat Activity Vocabulary as JSON, but rather as [JSON-LD]. Internally, it normalizes JSON to [JSON-LD expanded form]. Different ActivityPub implementations have slightly different JSON schema, and normalization allows for interoperability.

Zod takes the approach that the identifiers used in the input and output JSON are used in the program, which is too long and cumbersome for JSON-LD expanded form because the identifiers are [IRIs].

Validation, the main problem Zod solves, is already in place in the [@fedify/fedify/vocab] module, so you don't have to worry about it.

[JSON-LD]: https://json-ld.org/
[JSON-LD expanded form]: https://www.w3.org/TR/json-ld11/#expanded-document-form
[IRIs]: https://www.w3.org/TR/json-ld11/#iris
[@fedify/fedify/vocab]: https://jsr.io/@fedify/fedify/doc/vocab/~

**Comment by alexgleason** [comment]
Thank you for the explanation, that makes sense!

You could possibly use it for the Webfinger lookup, still.

Also, I wanted to tell you that your work inspired me so much that I shamelessly copied it! https://nostrify.dev/

Thank you for introducing me to Vitepress, it's an amazing super power. And I thought the name was great too. So, I created the sister project. :smiley:

**Comment by dahlia** [comment]
> You could possibly use it for the Webfinger lookup, still.

Alright, so I'll consider using Zod for the WebFinger schema.

> Also, I wanted to tell you that your work inspired me so much that I shamelessly copied it! https://nostrify.dev/

Cool project, I'll keep an eye on it.
